version: "3"
services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: cashmanager
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  deno:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      - PORT=80
      - DB_URI=mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/
      - DB=cashmanager
    depends_on:
      - mongo
    ports:
      - 80:80

volumes:
  mongodb:
