version: "3"
services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: cashmanager
    volumes:
      - mongodb:/data/db
    expose:
      - 27017

  deno:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    environment:
      DB_URI: ${DB_URI}
      PORT: 80
      DB: cashmanager
    depends_on:
      - mongo
    ports:
      - 80:80

volumes:
  mongodb:
