paths: 
  /api/accounts:
    get:
      summary: Get all bank account
      responses:
        '200':
          response: OK

    post:
      summary: create bank account
      responses:
        '201':
          response: CREATED

  /api/accounts/:account_num:
    get:
      summary: Get a bank account by ID
      parameters:
        - in: path
          name: account_num
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get
      responses:
        '200':
          response: OK

    put:
      summary: Update a bank account by ID
      parameters:
        - in: path
          name: account_num
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get

    delete:
      summary: Delete a bank account ID
      parameters:
        - in: path
          name: account_num
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get