paths: 
  /api/accounts:
    get:
      summary: Get all bank account
      responses:
        '200':
          response: OK

    post:
      summary: create bank account
      responses:
        '201':
          response: CREATED
        '403'
          response: Forbidden
    post:
      summary: log in bank account
      responses:
        '200':
          response: OK
        '401':
          response: Unauthorized

  /api/accounts/:account_num:
    get:
      summary: Get a bank account by ID
      parameters:
        - in: path
          name: account_num
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get
      responses:
        '200':
          response: OK
        '404':
          response: Not Found

    put:
      summary: Update a bank account by ID
      parameters:
        - in: path
          name: account_num
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get
      responses:
        '200':
          response: OK
        '404':
          response: Not Found

    delete:
      summary: Delete a bank account ID
      parameters:
        - in: path
          name: account_num
          schema:
            type: integer
          required: true
          description: Numeric ID of the account to get
      responses:
        '200':
          response: OK
        '404':
          response: Not Found
  /api/transactions:
    post: 
      summary: create transaction
      responses:
        '201':
          response: CREATED  