name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  APP_MONGO_USER: root
  APP_MONGO_PASS: root
  APP_MONGO_DB: cashmanager

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: cashmanager
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      #- name: Run linter
      ##  run: deno lint

      - name: Check Mongo is Up
        run: curl mongo:27017

      - name: Run server
        run: deno run --allow-net --allow-read --allow-env src/server.ts

      - name: Run tests
        run: deno test --allow-net