name: Deno CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run server
        env:
          DB_URI: ${{ secrets.DB_URI }}
          DB_NAME: cashmanagertest
        run: deno run -A src/server.ts &

      - name: Run tests
        run: deno test --allow-net
