name: Build and publish Docker image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: cash-manager-api
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push to registry
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: rg.fr-par.scw.cloud/funcscwcashmanagerfggvocmz
        username: nologin
        password: ${{ secrets.SCW_SECRET_KEY }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"
